### ISSUE TITLE
SonarQube service endpoint fails with token, succeeds with password

### ISSUE THREAD

**Issue by sawpresto** [nwcadence/java-dev-vsts#17]
Using `admin` as the username and a token generated in SonarQube, Build reports a 401 (not authorized) in Maven. However, using the password for the admin username succeeds. Removing the username/leaving the username field blank produces a similar error as well. SonarQube version is 6.4.0.

With admin username
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project myshuttle: Not authorized. Please check the properties sonar.login and sonar.password. -> [Help 1]
2017-07-26T22:25:02.2096450Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project myshuttle: Not authorized. Please check the properties sonar.login and sonar.password.
2017-07-26T22:25:02.2141970Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
2017-07-26T22:25:02.2154460Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
2017-07-26T22:25:02.2166770Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
2017-07-26T22:25:02.2182160Z 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
2017-07-26T22:25:02.2196600Z 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
2017-07-26T22:25:02.2210900Z 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
2017-07-26T22:25:02.2224670Z 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2017-07-26T22:25:02.2295450Z 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
2017-07-26T22:25:02.2309960Z 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
2017-07-26T22:25:02.2325910Z 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
2017-07-26T22:25:02.2342710Z 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
2017-07-26T22:25:02.2359240Z 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
2017-07-26T22:25:02.2373050Z 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
2017-07-26T22:25:02.2390130Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-26T22:25:02.2406040Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-26T22:25:02.2421930Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-26T22:25:02.2443850Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-26T22:25:02.2458580Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
2017-07-26T22:25:02.2472810Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
2017-07-26T22:25:02.2489750Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
2017-07-26T22:25:02.2504440Z 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2017-07-26T22:25:02.2520730Z Caused by: org.apache.maven.plugin.MojoExecutionException: Not authorized. Please check the properties sonar.login and sonar.password.
2017-07-26T22:25:02.2540110Z 	at org.sonarsource.scanner.maven.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:36)
2017-07-26T22:25:02.2555860Z 	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:80)
2017-07-26T22:25:02.2570080Z 	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:139)
2017-07-26T22:25:02.2586820Z 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
2017-07-26T22:25:02.2608110Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
2017-07-26T22:25:02.2647820Z 	... 20 more
2017-07-26T22:25:02.2662110Z Caused by: Not authorized. Please check the properties sonar.login and sonar.password.
2017-07-26T22:25:02.2697760Z [ERROR] 
2017-07-26T22:25:02.2717870Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2017-07-26T22:25:02.2739450Z [ERROR] 
2017-07-26T22:25:02.2753450Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2017-07-26T22:25:02.2767840Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2017-07-26T22:25:02.2807270Z /usr/share/maven/bin/mvn failed with return code: 1
2017-07-26T22:25:02.2833750Z Could not retrieve code analysis results - Maven run failed.
```
Without admin username:
```
##[debug]Request failed because the status code was: 401
2017-07-26T22:29:48.8375810Z Server responded with an invalid or unexpected response format.
2017-07-26T22:29:48.8388990Z Code analysis failed.
2017-07-26T22:29:48.8409240Z ##[debug]Request failed because the status code was: 401
```

**Comment by sawpresto** [comment]
Looks like due to the Maven task only using the generic endpoint and the logic within the VSTS task itself, the token can only be passed through if it's in the username field (sonar.login) instead of the password field. So it's much better to use username/password and is more secure. https://docs.sonarqube.org/display/SONAR/User+Token
